WAIT WINDOW (STR(msgbox("ALBEN › SOCIEDAD DE RESPONSABILIDAD LIMITADA", " About ", 4, "Message", "C")))
WAIT WINDOW (STR(msgbox("ALBEN › SOCIEDAD DE RESPONSABILIDAD LIMITADA", " About ", 4, "Message", "L")))

WAIT WINDOW (STR(msgbox("ALBEN › SOCIEDAD DE RESPONSABILIDAD LIMITADA", " About ", 4, "alert", "C")))
WAIT WINDOW (STR(msgbox("ALBEN › SOCIEDAD DE RESPONSABILIDAD LIMITADA", " Acerca de... ", 4, "alert", "L")))

WAIT WINDOW (STR(msgbox("ALBEN ", " About ", 4, "Message", "C")))
WAIT WINDOW (STR(msgbox("ALBEN › SOCIEDAD ", " About ", 4, "Message", "L")))

WAIT WINDOW (STR(msgbox("ALBEN", " About ", 4, "alert", "C")))
WAIT WINDOW (STR(msgbox("ALBEN LIMITADA", " Acerca de... ", 4, "alert", "L")))
WAIT WINDOW (STR(msgbox("El nombre del art¡culo no puede quedar en blanco", "", 0, "alert", "L")))
=msgbox("­ EL NOMBRE DEL ARTICULO NO PUEDE QUEDAR EN BLANCO !", "", 0, "message", "L")