** C.M. S.R.L. ** && Condensado.
E** C.M. S.R.L. **F  && Normal Negrita.
2** C.M. S.R.L. **    && 6lpi.
0** C.M. S.R.L. **    && 8lpi.
P** C.M. S.R.L. **    && 10lpi.
M** C.M. S.R.L. **    && 12lpi.
-** C.M. S.R.L. **-{NULL}  && Subrayado.

-** C.M. S.R.L. **T  && Subrayado.
-** C.M. S.R.L. **F  && Subrayado.
-** C.M. S.R.L. **5  && Subrayado.

4** C.M. S.R.L. **5  && Cursiva.
S{NULL}** C.M. S.R.L. **T  && Super.
S** C.M. S.R.L. **T  && Super.
E** C.M. S.R.L. **F  && Normal Negrita.